name: ebook
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_pdfviewer: ^27.2.2 
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_lints: ^5.0.0
  flutter_launcher_icons: 0.11.0
  http: ^1.2.2
  file_picker: ^8.1.4
  epub_view: ^3.2.0
  epubx: ^4.0.0
  flutter_colorpicker: ^1.0.3
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/walkingduck.gif
    - assets/images/readingduck.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/readingduck.png"
